version: '2.2'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${VERSION}
    container_name: es01
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "network.host="
      - "transport.host=127.0.0.1"
      - "http.host=0.0.0.0"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:${VERSION}
    container_name: kibana
    environment:
      SERVERNAME: localhost
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    depends_on:
      - es01
    ports:
      - "56011:5601"
    networks:
      - elastic

  ubuntu:
    container_name: ubuntu_ansible
    build:
      context: ../
      dockerfile: tests/Dockerfile
      args:
        BEAT_TYPE: ${BEAT_TYPE}
        CONTAINER_PERSIST: ${CONTAINER_PERSIST}
    depends_on:
      - es01
    networks:
      - elastic

networks:
  elastic:
    driver: bridge